---
# tasks file for sudo_users

- name: Adding users to wheel group (CentOS/RHELL)...
  user:
    name: "{{ item }}"
    groups: "wheel"
    append: yes
  loop:
    - User1
    - User2
  when: ansible_os_family == "RedHat"

- name: Adding users to sudo group (Debian/Ubuntu)...
  user:
    name: "{{ item }}"
    groups: "sudo"
    append: yes
  loop:
    - User1
    - User2
  when: ansible_os_family == "Debian"