---
# tasks file for create_users

- name: Creating users...
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop:
    - User1
    - User2
